#!/bin/bash

EMCC="/static/maarten/nobackup/build-from-source/emscripten/emcc"

"$EMCC" -O3 -std=c++11 -DNDEBUG -s TOTAL_MEMORY=33554432 ../2048.cpp ../Minimax.cpp ../JS_Minimax.cpp -o MiniMax2048.html -s EXPORTED_FUNCTIONS="['_JS_MinimaxBestMove']"

cp MiniMax2048.js /static/maarten/nobackup/build-from-source/2048/js/MiniMax2048.js
